version: '3'
services:
  php:
    build:
      context: ""
      dockerfile: build/Dockerfile
    container_name: project
    volumes:
      - '../var/www:/var/www/'
      - '../var/www/html:/var/www/html'
    working_dir: /var/www
    ports:
      - 8080:80
    links:
      - dbserver

  dbserver:
      build:
        context: ""
        dockerfile: build/mysql
      container_name: mysql
      environment:
          - TZ=Asia/Tokyo
          - MYSQL_USER=user
          - MYSQL_PASSWORD=pass
          - MYSQL_ROOT_PASSWORD=pass
          - MYSQL_DATABASE=project
      ports:
       - 3306:3306
      hostname: dbserver
