version: '3.8'

services:
  web:
    build: build
    ports:
      - "8080:80"
    volumes:
      - ../var/www/html:/var/www/html
    depends_on:
      - db
    networks:
      - lampnet

  db:
    image: mysql:8.2
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - lampnet

volumes:
  db_data:

networks:
  lampnet:
